// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFdwEjRnq1-Wbbsu94S1bwZn-ZJ0B1pEI',
    appId: '1:551128520698:web:086e63b8e9c61efc013643',
    messagingSenderId: '551128520698',
    projectId: 'flowboard-app-7539',
    authDomain: 'flowboard-app-7539.firebaseapp.com',
    storageBucket: 'flowboard-app-7539.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMexxGMD58FjBv_mIqsudgplyBG9kT-k',
    appId: '1:551128520698:android:c74add19e657ab46013643',
    messagingSenderId: '551128520698',
    projectId: 'flowboard-app-7539',
    storageBucket: 'flowboard-app-7539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG4bM8cuZx63n5XnYNODO0x7T6k2UPBk8',
    appId: '1:551128520698:ios:9b54dd563ad628d2013643',
    messagingSenderId: '551128520698',
    projectId: 'flowboard-app-7539',
    storageBucket: 'flowboard-app-7539.firebasestorage.app',
    iosBundleId: 'com.flowboard.flowboard',
  );
}
